package com.cuju.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class CujuColorScheme(
    val allGood: Color,
    val caution: Color,
    val cautionBackground: Color,
    val contentPrimary: Color,
    val contentSecondary: Color,
    val contentTertiary: Color,
    val contentInversePrimary: Color,
    val contentInverseSecondary: Color,
    val contentInverseTertiary: Color,
    val contentAccent: Color,
    val backgroundPrimary: Color,
    val backgroundSecondary: Color,
    val backgroundTertiary: Color,
    val backgroundAccent: Color,
    val backgroundAccentLight: Color,
    val backgroundInversePrimary: Color,
    val backgroundInverseSecondary: Color,
    val borderOpaque: Color,
    val borderTransparent: Color,
    val borderSelected: Color,
    val borderInverseOpaque: Color,
    val borderInverseTransparent: Color,
    val borderInverseSelected: Color,
    val contentStateDisabled: Color,
    val contentOnColor: Color,
    val contentOnColorInverse: Color,
    val contentInfo: Color,
    val contentNegative: Color,
    val contentWarning: Color,
    val contentPositive: Color,
    val backgroundStateDisabled: Color,
    val backgroundInfo: Color,
    val backgroundNegative: Color,
    val backgroundWarning: Color,
    val backgroundPositive: Color,
    val backgroundLightInfo: Color,
    val backgroundLightNegative: Color,
    val backgroundLightWarning: Color,
    val backgroundLightPositive: Color,
    val backgroundOverlay: Color,
    val borderStateDisabled: Color,
    val borderInfo: Color,
    val borderNegative: Color,
    val borderWarning: Color,
    val borderPositive: Color,
)

val Color.mediumEmphasis: Color get() = copy(alpha = 0.60f)
val Color.highEmphasis: Color get() = copy(alpha = 0.75f)
val Color.inactive: Color get() = copy(alpha = 0.54f)
val Color.disabled: Color get() = copy(alpha = 0.38f)
val Color.lowEmphasis: Color get() = copy(alpha = 0.14f)
val Color.lowestEmphasis: Color get() = copy(alpha = 0.08f)
val Color.focusVariant1: Color get() = copy(alpha = 0.32f)
val Color.focusVariant2: Color get() = copy(alpha = 0.12f)
val Color.hover: Color get() = copy(alpha = 0.08f)
val Color.border: Color get() = copy(alpha = 0.16f)
val Color.opacity8: Color get() = copy(alpha = 0.08f)
val Color.opacity12: Color get() = copy(alpha = 0.12f)
val Color.opacity16: Color get() = copy(alpha = 0.16f)
val Color.opacity20: Color get() = copy(alpha = 0.20f)
val Color.opacity25: Color get() = copy(alpha = 0.25f)
val Color.opacity50: Color get() = copy(alpha = 0.50f)

val LocalCujuColorScheme = staticCompositionLocalOf {
    CujuColorScheme(
        allGood = Color.Unspecified,
        caution = Color.Unspecified,
        cautionBackground = Color.Unspecified,
        contentPrimary = Color.Unspecified,
        contentSecondary = Color.Unspecified,
        contentTertiary = Color.Unspecified,
        contentInversePrimary = Color.Unspecified,
        contentInverseSecondary = Color.Unspecified,
        contentInverseTertiary = Color.Unspecified,
        contentAccent = Color.Unspecified,
        backgroundPrimary = Color.Unspecified,
        backgroundSecondary = Color.Unspecified,
        backgroundTertiary = Color.Unspecified,
        backgroundAccent = Color.Unspecified,
        backgroundAccentLight = Color.Unspecified,
        backgroundInversePrimary = Color.Unspecified,
        backgroundInverseSecondary = Color.Unspecified,
        borderOpaque = Color.Unspecified,
        borderTransparent = Color.Unspecified,
        borderSelected = Color.Unspecified,
        borderInverseOpaque = Color.Unspecified,
        borderInverseTransparent = Color.Unspecified,
        borderInverseSelected = Color.Unspecified,
        contentStateDisabled = Color.Unspecified,
        contentOnColor = Color.Unspecified,
        contentOnColorInverse = Color.Unspecified,
        contentInfo = Color.Unspecified,
        contentNegative = Color.Unspecified,
        contentWarning = Color.Unspecified,
        contentPositive = Color.Unspecified,
        backgroundStateDisabled = Color.Unspecified,
        backgroundInfo = Color.Unspecified,
        backgroundNegative = Color.Unspecified,
        backgroundWarning = Color.Unspecified,
        backgroundPositive = Color.Unspecified,
        backgroundLightInfo = Color.Unspecified,
        backgroundLightNegative = Color.Unspecified,
        backgroundLightWarning = Color.Unspecified,
        backgroundLightPositive = Color.Unspecified,
        backgroundOverlay = Color.Unspecified,
        borderStateDisabled = Color.Unspecified,
        borderInfo = Color.Unspecified,
        borderNegative = Color.Unspecified,
        borderWarning = Color.Unspecified,
        borderPositive = Color.Unspecified,
    )
}

fun lightCujuColorScheme(
    allGood: Color = Color(0xff36cc53),
    caution: Color = Color(0xffefab01),
    cautionBackground: Color = Color(0xff8a6e01),
    contentPrimary: Color = Color(0xff000000),
    contentSecondary: Color = Color(0xff4b4b4b),
    contentTertiary: Color = Color(0xff767676),
    contentInversePrimary: Color = Color(0xffffffff),
    contentInverseSecondary: Color = Color(0xffdddddd),
    contentInverseTertiary: Color = Color(0xffa6a6a6),
    contentAccent: Color = Color(0xff00a3e0),
    backgroundPrimary: Color = Color(0xffffffff),
    backgroundSecondary: Color = Color(0xfff2f2f2),
    backgroundTertiary: Color = Color(0xffe8e8e8),
    backgroundAccent: Color = Color(0xff62d5ff),
    backgroundAccentLight: Color = Color(0xffe7f5f8),
    backgroundInversePrimary: Color = Color(0xff000000),
    backgroundInverseSecondary: Color = Color(0xff4b4b4b),
    borderOpaque: Color = Color(0xffe8e8e8),
    borderTransparent: Color = Color(0x14000000),
    borderSelected: Color = Color(0xff00a3e0),
    borderInverseOpaque: Color = Color(0xff4b4b4b),
    borderInverseTransparent: Color = Color(0x33ffffff),
    borderInverseSelected: Color = Color(0xff00a3e0),
    contentStateDisabled: Color = Color(0xffbdbdbd),
    contentOnColor: Color = Color(0xffffffff),
    contentOnColorInverse: Color = Color(0xff000000),
    contentInfo: Color = Color(0xff00a3e0),
    contentNegative: Color = Color(0xffe52009),
    contentWarning: Color = Color(0xff8a6e01),
    contentPositive: Color = Color(0xff218334),
    backgroundStateDisabled: Color = Color(0xfff2f2f2),
    backgroundInfo: Color = Color(0xff46c9f8),
    backgroundNegative: Color = Color(0xffe52009),
    backgroundWarning: Color = Color(0xfffecc02),
    backgroundPositive: Color = Color(0xff63cf70),
    backgroundLightInfo: Color = Color(0xffe7f5f8),
    backgroundLightNegative: Color = Color(0xfffeedea),
    backgroundLightWarning: Color = Color(0xfffff8e0),
    backgroundLightPositive: Color = Color(0xffe8f5ea),
    backgroundOverlay: Color = Color(0x80000000),
    borderStateDisabled: Color = Color(0xfff2f2f2),
    borderInfo: Color = Color(0xff00a3e0),
    borderNegative: Color = Color(0xffe52009),
    borderWarning: Color = Color(0xff8a6e01),
    borderPositive: Color = Color(0xff218334),
): CujuColorScheme {
    return CujuColorScheme(
        allGood = allGood,
        caution = caution,
        cautionBackground = cautionBackground,
        contentPrimary = contentPrimary,
        contentSecondary = contentSecondary,
        contentTertiary = contentTertiary,
        contentInversePrimary = contentInversePrimary,
        contentInverseSecondary = contentInverseSecondary,
        contentInverseTertiary = contentInverseTertiary,
        contentAccent = contentAccent,
        backgroundPrimary = backgroundPrimary,
        backgroundSecondary = backgroundSecondary,
        backgroundTertiary = backgroundTertiary,
        backgroundAccent = backgroundAccent,
        backgroundAccentLight = backgroundAccentLight,
        backgroundInversePrimary = backgroundInversePrimary,
        backgroundInverseSecondary = backgroundInverseSecondary,
        borderOpaque = borderOpaque,
        borderTransparent = borderTransparent,
        borderSelected = borderSelected,
        borderInverseOpaque = borderInverseOpaque,
        borderInverseTransparent = borderInverseTransparent,
        borderInverseSelected = borderInverseSelected,
        contentStateDisabled = contentStateDisabled,
        contentOnColor = contentOnColor,
        contentOnColorInverse = contentOnColorInverse,
        contentInfo = contentInfo,
        contentNegative = contentNegative,
        contentWarning = contentWarning,
        contentPositive = contentPositive,
        backgroundStateDisabled = backgroundStateDisabled,
        backgroundInfo = backgroundInfo,
        backgroundNegative = backgroundNegative,
        backgroundWarning = backgroundWarning,
        backgroundPositive = backgroundPositive,
        backgroundLightInfo = backgroundLightInfo,
        backgroundLightNegative = backgroundLightNegative,
        backgroundLightWarning = backgroundLightWarning,
        backgroundLightPositive = backgroundLightPositive,
        backgroundOverlay = backgroundOverlay,
        borderStateDisabled = borderStateDisabled,
        borderInfo = borderInfo,
        borderNegative = borderNegative,
        borderWarning = borderWarning,
        borderPositive = borderPositive
    )
}

fun darkCujuColorScheme(
    allGood: Color = Color(0xff36cc53),
    caution: Color = Color(0xffefab01),
    cautionBackground: Color = Color(0xff8a6e01),
    contentPrimary: Color = Color(0xffffffff),
    contentSecondary: Color = Color(0xffdddddd),
    contentTertiary: Color = Color(0xffa6a6a6),
    contentInversePrimary: Color = Color(0xff000000),
    contentInverseSecondary: Color = Color(0xff4b4b4b),
    contentInverseTertiary: Color = Color(0xff767676),
    contentAccent: Color = Color(0xff00b4f5),
    backgroundPrimary: Color = Color(0xff000000),
    backgroundSecondary: Color = Color(0xff323435),
    backgroundTertiary: Color = Color(0xff4b4b4b),
    backgroundAccent: Color = Color(0xff00b4f5),
    backgroundAccentLight: Color = Color(0xff002d3d),
    backgroundInversePrimary: Color = Color(0xffffffff),
    backgroundInverseSecondary: Color = Color(0xffdddddd),
    borderOpaque: Color = Color(0xff4b4b4b),
    borderTransparent: Color = Color(0x33ffffff),
    borderSelected: Color = Color(0xff00b4f5),
    borderInverseOpaque: Color = Color(0xffe8e8e8),
    borderInverseTransparent: Color = Color(0x14000000),
    borderInverseSelected: Color = Color(0xff00b4f5),
    contentStateDisabled: Color = Color(0xff5e5e5e),
    contentOnColor: Color = Color(0xffffffff),
    contentOnColorInverse: Color = Color(0xff000000),
    contentInfo: Color = Color(0xff00b4f5),
    contentNegative: Color = Color(0xfffc7f79),
    contentWarning: Color = Color(0xffc6a002),
    contentPositive: Color = Color(0xff36bf4d),
    backgroundStateDisabled: Color = Color(0xff323435),
    backgroundInfo: Color = Color(0xff03668b),
    backgroundNegative: Color = Color(0xfffc7f79),
    backgroundWarning: Color = Color(0xff6e5e1b),
    backgroundPositive: Color = Color(0xff1a6c2b),
    backgroundLightInfo: Color = Color(0xff002d3d),
    backgroundLightNegative: Color = Color(0xff4e0b03),
    backgroundLightWarning: Color = Color(0xff302806),
    backgroundLightPositive: Color = Color(0xff0c3114),
    backgroundOverlay: Color = Color(0x80000000),
    borderStateDisabled: Color = Color(0xff323435),
    borderInfo: Color = Color(0xff00b4f5),
    borderNegative: Color = Color(0xfffc7f79),
    borderWarning: Color = Color(0xffc6a002),
    borderPositive: Color = Color(0xff36bf4d),
): CujuColorScheme {
    return CujuColorScheme(
        allGood = allGood,
        caution = caution,
        cautionBackground = cautionBackground,
        contentPrimary = contentPrimary,
        contentSecondary = contentSecondary,
        contentTertiary = contentTertiary,
        contentInversePrimary = contentInversePrimary,
        contentInverseSecondary = contentInverseSecondary,
        contentInverseTertiary = contentInverseTertiary,
        contentAccent = contentAccent,
        backgroundPrimary = backgroundPrimary,
        backgroundSecondary = backgroundSecondary,
        backgroundTertiary = backgroundTertiary,
        backgroundAccent = backgroundAccent,
        backgroundAccentLight = backgroundAccentLight,
        backgroundInversePrimary = backgroundInversePrimary,
        backgroundInverseSecondary = backgroundInverseSecondary,
        borderOpaque = borderOpaque,
        borderTransparent = borderTransparent,
        borderSelected = borderSelected,
        borderInverseOpaque = borderInverseOpaque,
        borderInverseTransparent = borderInverseTransparent,
        borderInverseSelected = borderInverseSelected,
        contentStateDisabled = contentStateDisabled,
        contentOnColor = contentOnColor,
        contentOnColorInverse = contentOnColorInverse,
        contentInfo = contentInfo,
        contentNegative = contentNegative,
        contentWarning = contentWarning,
        contentPositive = contentPositive,
        backgroundStateDisabled = backgroundStateDisabled,
        backgroundInfo = backgroundInfo,
        backgroundNegative = backgroundNegative,
        backgroundWarning = backgroundWarning,
        backgroundPositive = backgroundPositive,
        backgroundLightInfo = backgroundLightInfo,
        backgroundLightNegative = backgroundLightNegative,
        backgroundLightWarning = backgroundLightWarning,
        backgroundLightPositive = backgroundLightPositive,
        backgroundOverlay = backgroundOverlay,
        borderStateDisabled = borderStateDisabled,
        borderInfo = borderInfo,
        borderNegative = borderNegative,
        borderWarning = borderWarning,
        borderPositive = borderPositive
    )
}

val lightCujuMaterialColorScheme = lightColorScheme(
    primary = Color(0xff000000),
    onPrimary = Color(0xffffffff),
    primaryContainer = Color(0xfff2f2f2),
    onPrimaryContainer = Color(0xff000000),
    secondary = Color(0xff4b4b4b),
    onSecondary = Color(0xffffffff),
    secondaryContainer = Color(0xffe8e8e8),
    onSecondaryContainer = Color(0xff000000),
    tertiary = Color(0xff767676),
    onTertiary = Color(0xffffffff),
    tertiaryContainer = Color(0xffe8e8e8),
    onTertiaryContainer = Color(0xff000000),
    error = Color(0xffe52009),
    onError = Color(0xffffffff),
    errorContainer = Color(0xfffeedea),
    onErrorContainer = Color(0xff000000),
    background = Color(0xffffffff),
    onBackground = Color(0xff000000),
    surface = Color(0xffffffff),
    onSurface = Color(0xff000000),
    surfaceVariant = Color(0xfff2f2f2),
    onSurfaceVariant = Color(0xff4b4b4b),
    outline = Color(0xffe8e8e8),
    outlineVariant = Color(0xffe8e8e8),
    surfaceTint = Color(0xffa6a6a6),
    scrim = Color(0xff000000),
    inverseSurface = Color(0xff000000),
    inverseOnSurface = Color(0xffffffff),
    inversePrimary = Color(0xffffffff),
    surfaceDim = Color(0xfff2f2f2),
    surfaceBright = Color(0xffffffff),
    surfaceContainerLowest = Color(0xffffffff),
    surfaceContainerLow = Color(0xffffffff),
    surfaceContainer = Color(0xfff2f2f2),
    surfaceContainerHigh = Color(0xffe8e8e8),
    surfaceContainerHighest = Color(0xffe8e8e8)
)

val darkCujuMaterialColorScheme = darkColorScheme(
    primary = Color(0xffd3bcfd),
    onPrimary = Color(0xff38265c),
    primaryContainer = Color(0xff4f3d74),
    onPrimaryContainer = Color(0xffebddff),
    inversePrimary = Color(0xff68548e),
    secondary = Color(0xffcdc2db),
    onSecondary = Color(0xff342d40),
    secondaryContainer = Color(0xff4b4358),
    onSecondaryContainer = Color(0xffe9def8),
    tertiary = Color(0xfff0b7c5),
    onTertiary = Color(0xff4a2530),
    tertiaryContainer = Color(0xff643b46),
    onTertiaryContainer = Color(0xffffd9e1),
    background = Color(0xff151218),
    onBackground = Color(0xffe7e0e8),
    surface = Color(0xff151218),
    onSurface = Color(0xffe7e0e8),
    surfaceVariant = Color(0xff49454e),
    onSurfaceVariant = Color(0xffcbc4cf),
    surfaceTint = Color(0xffd3bcfd),
    inverseSurface = Color(0xffe7e0e8),
    inverseOnSurface = Color(0xff322f35),
    error = Color(0xffffb4ab),
    onError = Color(0xff690005),
    errorContainer = Color(0xff93000a),
    onErrorContainer = Color(0xffffdad6),
    outline = Color(0xff948f99),
    outlineVariant = Color(0xff49454e),
    scrim = Color(0xff000000),
    surfaceBright = Color(0xff3b383e),
    surfaceContainer = Color(0xff211f24),
    surfaceContainerHigh = Color(0xff2c292f),
    surfaceContainerHighest = Color(0xff36343a),
    surfaceContainerLow = Color(0xff1d1b20),
    surfaceContainerLowest = Color(0xff0f0d13),
    surfaceDim = Color(0xff151218)
)
